version: '3.4'

services:
  database:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5532:5432'
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    image: paymentsgateway
    build:
      context: src
      dockerfile: PaymentsGateway.API/Dockerfile
    ports:
      - '3000:80'
    depends_on:
      - database
volumes:
  database:
    driver: local